//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhAn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examination_view
    {
        public string examinateID { get; set; }
        public string Employeename { get; set; }
        public string Patientname { get; set; }
        public int breathing { get; set; }
        public System.DateTime examinateDay { get; set; }
        public double height { get; set; }
        public string symptom { get; set; }
        public double temperature { get; set; }
        public int veins { get; set; }
        public double weight { get; set; }
    }
}
