//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhAn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class info_Employee
    {
        public string peopleID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string sex { get; set; }
        public System.DateTime birthDay { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string cardID { get; set; }
        public string position { get; set; }
        public string departmentID { get; set; }
    }
}
