//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhAn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicalRecord
    {
        public string patientID { get; set; }
        public string patientFirstName { get; set; }
        public string patientLastname { get; set; }
        public string sex { get; set; }
        public System.DateTime birthDay { get; set; }
        public string healthInsurance_ { get; set; }
        public string doctorID { get; set; }
        public string doctorFirstname { get; set; }
        public string doctorLastName { get; set; }
        public System.DateTime examinateDay { get; set; }
        public double height { get; set; }
        public double weight { get; set; }
        public double temperature { get; set; }
        public int breathing { get; set; }
        public string symptom { get; set; }
        public int veins { get; set; }
        public System.DateTime createdAt { get; set; }
    }
}
