//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhAn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pay_view
    {
        public string patientName { get; set; }
        public string employeeName { get; set; }
        public string receiptName { get; set; }
        public Nullable<int> payTotal { get; set; }
        public System.DateTime createdAt { get; set; }
    }
}
