//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhAn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pre_Medicines
    {
        public string patientID { get; set; }
        public string employeeID { get; set; }
        public string medicineId { get; set; }
        public string prescriptionId { get; set; }
        public string pre_MedicineId { get; set; }
        public int amount { get; set; }
    
        public virtual Prescription Prescription { get; set; }
    }
}
