//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhAn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription_Medicines
    {
        public string patientID { get; set; }
        public string patientFirstName { get; set; }
        public string patientLastname { get; set; }
        public System.DateTime birthDay { get; set; }
        public string doctorID { get; set; }
        public string doctorFirstname { get; set; }
        public string doctorLastName { get; set; }
        public string medicineID { get; set; }
        public string medicineName { get; set; }
        public string unit { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    }
}
